# Generated by Django 2.2.8 on 2019-12-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expimpmembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='academic_group_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Шифр навчальної групи'),
        ),
    ]
