# Generated by Django 2.2.8 on 2019-12-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expimpmembers', '0002_auto_20191220_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='id_number',
            field=models.CharField(default='Невідомо', max_length=50, primary_key=True, serialize=False, verbose_name='Номер студентського квитка'),
        ),
    ]
