# Generated by Django 2.2.8 on 2019-12-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expimpmembers', '0003_auto_20191220_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='academic_group_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expimpmembers.Faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='member',
            name='academic_group_of_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expimpmembers.AcademicGroup', verbose_name='Академічна група'),
        ),
    ]
